version: '3.3'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.app
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5004:5000
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - POSTGRES_USER=snotty
      - POSTGRES_PASSWORD=MasterSlobs
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=127.0.0.1

  api-db:  # new
    build:
      context: .
      dockerfile: Dockerfile.db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=snotty
      - POSTGRES_PASSWORD=MasterSlobs